### ISSUE TITLE
TsInterfaces with fields don't have their TS fields emitted

### ISSUE THREAD

**Issue by niloc132** [Vertispan/jsinterop-ts-defs#15]
Given a Java class annotated with `@TsInterface`, with `@JsProperty`-annotated fields (or simply public fields):

```java
@TsInterface
public class Person {
  @JsProperty
  public String name;
}
```

Actual result:
```typescript
export interface Person {

}
```

Expected result:
```typescript
export interface Person {
  get name():string;
  set name(name:string);
}
```

Note that if instead of a JsProperty-annotated field, the getter and setter methods are written in Java instead, then the interface will have the getter and setter.

**Comment by vegegoku** [comment]
Just a note here that when we have both the setter and getter we generate a field instead of 2 methods so actually that name set and get in the expected result will be generated as : 

```
export interface Person {
  name:string;
}
```

And it will be automatically get the set/get method by typescript.

**Comment by niloc132** [comment]
> So only in the case of `final` fields will be generating a getter.

Perfect, I was going to request that as an enhancement later, as it will almost certainly be more idiomatic this way.
