### ISSUE TITLE
Some is- getters are incorrectly having their names changed

### ISSUE THREAD

**Issue by niloc132** [Vertispan/jsinterop-ts-defs#29]
Example Java:
```java
    @JsProperty(name = "is3d")
    public boolean isIs3d() {
        return descriptor.getIs3d();
    }
```
Resulting property in ts:
```typescript
get 3d():boolean;
```

The main bug here is that the name of the property should be "is3d" as specified by JsProperty.name() (see/reopen #25 ?), but since typescript is generating this as "3d", that is an invalid identifier for TS/JS.

**Comment by vegegoku** [comment]
This is fixed in #33
