### ISSUE TITLE
Empty interfaces aren't emitted, and references to it are left as unknown

### ISSUE THREAD

**Issue by niloc132** [Vertispan/jsinterop-ts-defs#39]
Java:
```java
interface Foo {
  String getName();
}
interface Bar extends Foo {}

public class SomethingElse {
  public JsArray<Bar> getBar() {...}
}
```

As typescript is structurally typed, it could well make sense to omit Bar entirely (since Foo instances can freely be assigned to Bar variables), even though this doesn't make sense in Java. However, presently references to Bar disappear entirely, and become unknown. The output of the above looks something like this:

```typescript
export interface Foo {
  getName():string;
}
export class SomethingElse {
  getBar():Array<unknown>;
}
```

If Bar is omitted, then getBar() should return `Array<Foo>`. Otherwise, Bar should be included, so that we don't get `unknown`.

It is possible I can work around this with `@TsTypeRef`, I haven't tried carefully.

**Comment by vegegoku** [comment]
Do we expect interfaces to be automatically exported if used by an exported type/member? 

because in the sample above at least marking the Bar interface as JsType will emit the correct type in the getBar method.

that will force Bar interface to be exported, though Foo interface will not unless it is also marked as JsType.

**Comment by niloc132** [comment]
I wouldnt expect them to auto-export if used by an exported member, but if it has ts annotations on it i think I do expect it to be exported, since we do that elsewhere, though usually depend on some member being annotated. I think this is a reasonable use case though.

The use case I have is a little interesting, and I'm really not even certain if it makes sense in TS at all, but it makes sense in java and jsinterop. In java, the super-interface has jsinterop-annotated members, and the subtype doesn't expose any extra public or jsinterop members - but it is still a subtype. In TS terms, two types that have the same api are _the same type_, which gets a little silly in places.

So maybe the right answer here is to use `@TsTypeRef`? My limitation there will be that I'm actually using generics to expose that method... I'll file that later when I have a concrete answer of what I think I want the tool to do.

**Comment by niloc132** [comment]
Actually here's one usecase:

```java
@TsInterface
@TsName(namespace="ns")
public interface TypeOne {
  @JsMethod
  String name();
}
@TsInterface
@TsName(namespace="ns")
public interface TypeTwo {
  @JsMethod
  int age();
}
@TsInterface
@TsName(namespace="ns")
public interface Union extends TypeOne, TypeTwo {}
```

Here, i'm explicitly not putting JsType on these interfaces, since I don't want other members in them (omitted here) to be exposed since I'd have to just skip them all. I could put JsType on the Union type? and then explicitly JsIgnore every member in java...

That might make more sense too. I was worried we're going to have other cases where we want marker types to work, but since TS won't consider them to be different anyway, maybe it doesn't matter.

I'll think about this a bit more, but I think we can close it.
